name: CI for Python

# Run this workflow whenever a pull request is opened or updated
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Adjust the Python version as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt file

      # Run linting
      - name: Run Linter
        run: |
          pip install flake8
          flake8 .
